# Generated by Django 4.1.3 on 2022-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='imgTitle',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
