# Generated by Django 4.1.3 on 2022-11-28 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program_DB', '0002_news_imgtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='imgTitle',
        ),
        migrations.AlterField(
            model_name='administrators',
            name='birthdate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='administrators',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='admins/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='birthdate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='authors',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='authors/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='members',
            name='birthdate',
            field=models.DateField(default=None),
        ),
        migrations.CreateModel(
            name='Images_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgTitle', models.CharField(default=None, max_length=100)),
                ('img', models.ImageField(null=True, upload_to='news/%Y/%m')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image_news', to='program_DB.news')),
            ],
            options={
                'unique_together': {('news', 'imgTitle')},
            },
        ),
    ]
